#!/usr/bin/env python
"""
Figure 2 -- workflow schematic.

Not a data figure -- a diagram of the analysis pipeline, from raw ASTER
TIR input through the final FDR-corrected, robustness-checked result.
Boxes are grouped into four stages by color: data/processing (blue),
classification (orange), statistical testing (green), correction/
robustness (purple). Drawn with matplotlib patches, no external diagramming
tool, so it is regenerated by this script like every other figure.

Usage:
    conda run -n aster-minerals python scripts/fig02_workflow_schematic.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

REPO_ROOT = Path(__file__).parent.parent

STAGE_COLOR = {
    "data": "#E6F0FA",
    "classify": "#FDEBD3",
    "test": "#E3F2E9",
    "correct": "#F0E6F5",
}
STAGE_EDGE = {
    "data": "#0072B2",
    "classify": "#E69F00",
    "test": "#009E73",
    "correct": "#8E44AD",
}

# (label, x, y, width, height, stage)
BOXES = [
    ("ASTER L1T TIR\nbands B10–B14", 0.5, 9.0, 2.6, 1.0, "data"),
    ("Band ratios\nsilica / carbonate / mafic\n(B13/B14, B13/B12, B12/B13)", 0.5, 7.4, 2.6, 1.1, "data"),
    ("Multi-granule mosaic\n(feathered blend,\nbbox-clipped)", 0.5, 5.8, 2.6, 1.1, "data"),

    ("Percentile classification\n70th / 90th per ratio\n(3-class map)", 3.6, 7.4, 2.6, 1.1, "classify"),
    ("Combined score 0–6\n(sum of 3 class maps)", 3.6, 5.8, 2.6, 1.0, "classify"),
    ("Strong-anomaly zones\nscore ≥ 3, vectorized", 3.6, 4.3, 2.6, 1.0, "classify"),

    ("MRDS deposits\nfootprint-clipped,\ncritical-minerals only", 6.7, 5.8, 2.6, 1.1, "data"),

    ("Site-specific null p₀\nzone area / footprint area", 6.7, 4.3, 2.6, 1.0, "test"),
    ("Binomial test\n(primary)", 9.8, 5.4, 2.3, 0.9, "test"),
    ("Monte Carlo\npermutation", 9.8, 4.3, 2.3, 0.9, "test"),
    ("Continuous-score\nMann-Whitney U", 9.8, 3.2, 2.3, 0.9, "test"),

    ("Benjamini-Hochberg FDR\nacross all sites, 2 tests", 6.7, 2.0, 2.6, 1.0, "correct"),
    ("DBSCAN clustering\nsensitivity (250/500/1000 m)", 3.6, 2.0, 2.6, 1.0, "correct"),
    ("Threshold / score-cutoff\nsensitivity", 0.5, 2.0, 2.6, 1.0, "correct"),

    ("Final result:\n6 FDR-significant (binomial),\n11 union, 4 fully robust", 6.7, 0.3, 5.4, 1.1, "correct"),
]

ARROWS = [
    (0, 1), (1, 2),
    (2, 3), (3, 4), (4, 5),
    (5, 7),
    (6, 7),
    (7, 8), (7, 9), (7, 10),
    (8, 11), (9, 11), (10, 11),
    (11, 14), (12, 14), (13, 14),
    (5, 12), (4, 13),
]


def main() -> None:
    fig, ax = plt.subplots(figsize=(13, 8))
    centers = {}

    for i, (label, x, y, w, h, stage) in enumerate(BOXES):
        box = FancyBboxPatch(
            (x, y), w, h,
            boxstyle="round,pad=0.08,rounding_size=0.08",
            linewidth=1.4, edgecolor=STAGE_EDGE[stage], facecolor=STAGE_COLOR[stage],
            zorder=2,
        )
        ax.add_patch(box)
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center",
                fontsize=8.3, color="#222222", zorder=3)
        centers[i] = (x + w / 2, y + h / 2, x, y, w, h)

    for a, b in ARROWS:
        xa, ya, xa0, ya0, wa, ha = centers[a]
        xb, yb, xb0, yb0, wb, hb = centers[b]
        # connect from edge closest to target, roughly
        start = (xa, ya0) if yb < ya else (xa, ya0 + ha)
        if abs(xb - xa) > max(wa, wb):
            start = (xa0 + wa, ya) if xb > xa else (xa0, ya)
            end = (xb0, yb) if xb > xa else (xb0 + wb, yb)
        else:
            end = (xb, yb0 + hb) if yb > ya else (xb, yb0)
        arrow = FancyArrowPatch(
            start, end, arrowstyle="-|>", mutation_scale=12,
            linewidth=1.1, color="#555555", zorder=1, shrinkA=2, shrinkB=2,
        )
        ax.add_patch(arrow)

    legend_items = [
        ("Data / processing", STAGE_COLOR["data"], STAGE_EDGE["data"]),
        ("Classification", STAGE_COLOR["classify"], STAGE_EDGE["classify"]),
        ("Statistical testing", STAGE_COLOR["test"], STAGE_EDGE["test"]),
        ("Correction / robustness", STAGE_COLOR["correct"], STAGE_EDGE["correct"]),
    ]
    for i, (label, fc, ec) in enumerate(legend_items):
        ax.add_patch(FancyBboxPatch((0.5 + i * 3.1, -0.9), 0.3, 0.3,
                                     boxstyle="round,pad=0.02", facecolor=fc, edgecolor=ec))
        ax.text(0.9 + i * 3.1, -0.75, label, fontsize=8.5, va="center")

    ax.set_xlim(-0.3, 12.5)
    ax.set_ylim(-1.3, 10.3)
    ax.axis("off")
    ax.set_title("Figure 2 — analysis workflow, ASTER TIR to corrected significance result", fontsize=12)

    fig.tight_layout()
    out_path = REPO_ROOT / "figures" / "fig02_workflow_schematic.png"
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    print(f"Saved {out_path}")


if __name__ == "__main__":
    main()
